name: fhir_test

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  fhir_dstu2:
    path: ../fhir_dstu2
  fhir_primitives: ^0.1.0
  fhir_r4:
    path: ../fhir_r4
  fhir_r5: 
    path: ../fhir_r5
  fhir_r6:
    path: ../fhir_r6
  fhir_stu3:
    path: ../fhir_stu3
  http: ^1.2.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  recase: ^4.0.0


dev_dependencies:
  test: ^1.25.5
  build_runner: ^2.4.9
  freezed: ^2.5.3
  json_serializable: ^6.8.0
