enum VersionAlgorithm {
  @JsonValue('semver')
semver,
  @JsonValue('integer')
integer,
  @JsonValue('alpha')
alpha,
  @JsonValue('date')
date,
  @JsonValue('natural')
natural,
}

enum PublicationStatus {
  @JsonValue('draft')
draft,
  @JsonValue('active')
active,
  @JsonValue('retired')
retired,
  @JsonValue('unknown')
unknown,
}

enum CitationSummaryStyle {
  @JsonValue('vancouver')
vancouver,
  @JsonValue('ama11')
ama11,
  @JsonValue('apa7')
apa7,
  @JsonValue('apa6')
apa6,
  @JsonValue('asa6')
asa6,
  @JsonValue('mla8')
mla8,
  @JsonValue('cochrane')
cochrane,
  @JsonValue('elsevier-harvard')
elsevierharvard,
  @JsonValue('nature')
nature,
  @JsonValue('acs')
acs,
  @JsonValue('chicago-a-17')
chicagoa17,
  @JsonValue('chicago-b-17')
chicagob17,
  @JsonValue('ieee')
ieee,
  @JsonValue('comppub')
comppub,
}

enum CitationClassificationType {
  @JsonValue('citation-source')
citationsource,
  @JsonValue('medline-owner')
medlineowner,
  @JsonValue('fevir-platform-use')
fevirplatformuse,
}

enum CitationArtifactClassifier {
  @JsonValue('audio')
audio,
  @JsonValue('D001877')
d001877,
  @JsonValue('cds-artifact')
cdsartifact,
  @JsonValue('D016420')
d016420,
  @JsonValue('common-share')
commonshare,
  @JsonValue('D019991')
d019991,
  @JsonValue('D064886')
d064886,
  @JsonValue('dataset-unpublished')
datasetunpublished,
  @JsonValue('Electronic')
electronic,
  @JsonValue('Electronic-eCollection')
electronicecollection,
  @JsonValue('Electronic-Print')
electronicprint,
  @JsonValue('executable-app')
executableapp,
  @JsonValue('fhir-resource')
fhirresource,
  @JsonValue('image')
image,
  @JsonValue('interactive-form')
interactiveform,
  @JsonValue('D016428')
d016428,
  @JsonValue('D016422')
d016422,
  @JsonValue('machine-code')
machinecode,
  @JsonValue('medline-base')
medlinebase,
  @JsonValue('prediction-model')
predictionmodel,
  @JsonValue('D000076942')
d000076942,
  @JsonValue('Print')
print,
  @JsonValue('Print-Electronic')
printelectronic,
  @JsonValue('project-specific')
projectspecific,
  @JsonValue('protocol')
protocol,
  @JsonValue('pseudocode')
pseudocode,
  @JsonValue('D016425')
d016425,
  @JsonValue('standard-specification')
standardspecification,
  @JsonValue('terminology')
terminology,
  @JsonValue('D059040')
d059040,
  @JsonValue('webpage')
webpage,
}

enum CitationStatusType {
  @JsonValue('pubmed-pubstatus-received')
pubmedpubstatusreceived,
  @JsonValue('pubmed-pubstatus-accepted')
pubmedpubstatusaccepted,
  @JsonValue('pubmed-pubstatus-epublish')
pubmedpubstatusepublish,
  @JsonValue('pubmed-pubstatus-ppublish')
pubmedpubstatusppublish,
  @JsonValue('pubmed-pubstatus-revised')
pubmedpubstatusrevised,
  @JsonValue('pubmed-pubstatus-aheadofprint')
pubmedpubstatusaheadofprint,
  @JsonValue('pubmed-pubstatus-retracted')
pubmedpubstatusretracted,
  @JsonValue('pubmed-pubstatus-ecollection')
pubmedpubstatusecollection,
  @JsonValue('pubmed-pubstatus-pmc')
pubmedpubstatuspmc,
  @JsonValue('pubmed-pubstatus-pmcr')
pubmedpubstatuspmcr,
  @JsonValue('pubmed-pubstatus-pubmed')
pubmedpubstatuspubmed,
  @JsonValue('pubmed-pubstatus-pubmedr')
pubmedpubstatuspubmedr,
  @JsonValue('pubmed-pubstatus-premedline')
pubmedpubstatuspremedline,
  @JsonValue('pubmed-pubstatus-medline')
pubmedpubstatusmedline,
  @JsonValue('pubmed-pubstatus-medliner')
pubmedpubstatusmedliner,
  @JsonValue('pubmed-pubstatus-entrez')
pubmedpubstatusentrez,
  @JsonValue('pubmed-pubstatus-pmc-release')
pubmedpubstatuspmcrelease,
  @JsonValue('medline-completed')
medlinecompleted,
  @JsonValue('medline-in-process')
medlineinprocess,
  @JsonValue('medline-pubmed-not-medline')
medlinepubmednotmedline,
  @JsonValue('medline-in-data-review')
medlineindatareview,
  @JsonValue('medline-publisher')
medlinepublisher,
  @JsonValue('medline-medline')
medlinemedline,
  @JsonValue('medline-oldmedline')
medlineoldmedline,
  @JsonValue('pubmed-publication-status-ppublish')
pubmedpublicationstatusppublish,
  @JsonValue('pubmed-publication-status-epublish')
pubmedpublicationstatusepublish,
  @JsonValue('pubmed-publication-status-aheadofprint')
pubmedpublicationstatusaheadofprint,
}

enum CitationStatusType {
  @JsonValue('pubmed-pubstatus-received')
pubmedpubstatusreceived,
  @JsonValue('pubmed-pubstatus-accepted')
pubmedpubstatusaccepted,
  @JsonValue('pubmed-pubstatus-epublish')
pubmedpubstatusepublish,
  @JsonValue('pubmed-pubstatus-ppublish')
pubmedpubstatusppublish,
  @JsonValue('pubmed-pubstatus-revised')
pubmedpubstatusrevised,
  @JsonValue('pubmed-pubstatus-aheadofprint')
pubmedpubstatusaheadofprint,
  @JsonValue('pubmed-pubstatus-retracted')
pubmedpubstatusretracted,
  @JsonValue('pubmed-pubstatus-ecollection')
pubmedpubstatusecollection,
  @JsonValue('pubmed-pubstatus-pmc')
pubmedpubstatuspmc,
  @JsonValue('pubmed-pubstatus-pmcr')
pubmedpubstatuspmcr,
  @JsonValue('pubmed-pubstatus-pubmed')
pubmedpubstatuspubmed,
  @JsonValue('pubmed-pubstatus-pubmedr')
pubmedpubstatuspubmedr,
  @JsonValue('pubmed-pubstatus-premedline')
pubmedpubstatuspremedline,
  @JsonValue('pubmed-pubstatus-medline')
pubmedpubstatusmedline,
  @JsonValue('pubmed-pubstatus-medliner')
pubmedpubstatusmedliner,
  @JsonValue('pubmed-pubstatus-entrez')
pubmedpubstatusentrez,
  @JsonValue('pubmed-pubstatus-pmc-release')
pubmedpubstatuspmcrelease,
  @JsonValue('medline-completed')
medlinecompleted,
  @JsonValue('medline-in-process')
medlineinprocess,
  @JsonValue('medline-pubmed-not-medline')
medlinepubmednotmedline,
  @JsonValue('medline-in-data-review')
medlineindatareview,
  @JsonValue('medline-publisher')
medlinepublisher,
  @JsonValue('medline-medline')
medlinemedline,
  @JsonValue('medline-oldmedline')
medlineoldmedline,
  @JsonValue('pubmed-publication-status-ppublish')
pubmedpublicationstatusppublish,
  @JsonValue('pubmed-publication-status-epublish')
pubmedpublicationstatusepublish,
  @JsonValue('pubmed-publication-status-aheadofprint')
pubmedpublicationstatusaheadofprint,
}

enum CitedArtifactStatusType {
  @JsonValue('created')
created,
  @JsonValue('submitted')
submitted,
  @JsonValue('withdrawn')
withdrawn,
  @JsonValue('pre-review')
prereview,
  @JsonValue('under-review')
underreview,
  @JsonValue('post-review-pre-published')
postreviewprepublished,
  @JsonValue('rejected')
rejected,
  @JsonValue('published-early-form')
publishedearlyform,
  @JsonValue('published-final-form')
publishedfinalform,
  @JsonValue('accepted')
accepted,
  @JsonValue('archived')
archived,
  @JsonValue('retracted')
retracted,
  @JsonValue('draft')
draft,
  @JsonValue('active')
active,
  @JsonValue('approved')
approved,
  @JsonValue('unknown')
unknown,
}

enum CitedArtifactStatusType {
  @JsonValue('created')
created,
  @JsonValue('submitted')
submitted,
  @JsonValue('withdrawn')
withdrawn,
  @JsonValue('pre-review')
prereview,
  @JsonValue('under-review')
underreview,
  @JsonValue('post-review-pre-published')
postreviewprepublished,
  @JsonValue('rejected')
rejected,
  @JsonValue('published-early-form')
publishedearlyform,
  @JsonValue('published-final-form')
publishedfinalform,
  @JsonValue('accepted')
accepted,
  @JsonValue('archived')
archived,
  @JsonValue('retracted')
retracted,
  @JsonValue('draft')
draft,
  @JsonValue('active')
active,
  @JsonValue('approved')
approved,
  @JsonValue('unknown')
unknown,
}

enum TitleType {
  @JsonValue('primary')
primary,
  @JsonValue('official')
official,
  @JsonValue('scientific')
scientific,
  @JsonValue('plain-language')
plainlanguage,
  @JsonValue('subtitle')
subtitle,
  @JsonValue('short-title')
shorttitle,
  @JsonValue('acronym')
acronym,
  @JsonValue('earlier-title')
earliertitle,
  @JsonValue('language')
language,
  @JsonValue('autotranslated')
autotranslated,
  @JsonValue('human-use')
humanuse,
  @JsonValue('machine-use')
machineuse,
  @JsonValue('duplicate-uid')
duplicateuid,
}

enum CitedArtifactAbstractType {
  @JsonValue('primary-human-use')
primaryhumanuse,
  @JsonValue('primary-machine-use')
primarymachineuse,
  @JsonValue('truncated')
truncated,
  @JsonValue('short-abstract')
shortabstract,
  @JsonValue('long-abstract')
longabstract,
  @JsonValue('plain-language')
plainlanguage,
  @JsonValue('different-publisher')
differentpublisher,
  @JsonValue('language')
language,
  @JsonValue('autotranslated')
autotranslated,
  @JsonValue('duplicate-pmid')
duplicatepmid,
  @JsonValue('earlier-abstract')
earlierabstract,
}

enum CitedArtifactPartType {
  @JsonValue('pages')
pages,
  @JsonValue('sections')
sections,
  @JsonValue('paragraphs')
paragraphs,
  @JsonValue('lines')
lines,
  @JsonValue('tables')
tables,
  @JsonValue('figures')
figures,
  @JsonValue('supplement')
supplement,
  @JsonValue('supplement-subpart')
supplementsubpart,
  @JsonValue('article-set')
articleset,
}

enum CitationArtifactClassifier {
  @JsonValue('audio')
audio,
  @JsonValue('D001877')
d001877,
  @JsonValue('cds-artifact')
cdsartifact,
  @JsonValue('D016420')
d016420,
  @JsonValue('common-share')
commonshare,
  @JsonValue('D019991')
d019991,
  @JsonValue('D064886')
d064886,
  @JsonValue('dataset-unpublished')
datasetunpublished,
  @JsonValue('Electronic')
electronic,
  @JsonValue('Electronic-eCollection')
electronicecollection,
  @JsonValue('Electronic-Print')
electronicprint,
  @JsonValue('executable-app')
executableapp,
  @JsonValue('fhir-resource')
fhirresource,
  @JsonValue('image')
image,
  @JsonValue('interactive-form')
interactiveform,
  @JsonValue('D016428')
d016428,
  @JsonValue('D016422')
d016422,
  @JsonValue('machine-code')
machinecode,
  @JsonValue('medline-base')
medlinebase,
  @JsonValue('prediction-model')
predictionmodel,
  @JsonValue('D000076942')
d000076942,
  @JsonValue('Print')
print,
  @JsonValue('Print-Electronic')
printelectronic,
  @JsonValue('project-specific')
projectspecific,
  @JsonValue('protocol')
protocol,
  @JsonValue('pseudocode')
pseudocode,
  @JsonValue('D016425')
d016425,
  @JsonValue('standard-specification')
standardspecification,
  @JsonValue('terminology')
terminology,
  @JsonValue('D059040')
d059040,
  @JsonValue('webpage')
webpage,
}

enum PublishedInType {
  @JsonValue('D020492')
d020492,
  @JsonValue('D019991')
d019991,
  @JsonValue('D001877')
d001877,
  @JsonValue('D064886')
d064886,
}

enum CitedMedium {
  @JsonValue('internet')
internet,
  @JsonValue('print')
print,
  @JsonValue('offline-digital-storage')
offlinedigitalstorage,
  @JsonValue('internet-without-issue')
internetwithoutissue,
  @JsonValue('print-without-issue')
printwithoutissue,
  @JsonValue('offline-digital-storage-without-issue')
offlinedigitalstoragewithoutissue,
}

enum ArtifactUrlClassifier {
  @JsonValue('abstract')
abstract,
  @JsonValue('full-text')
fulltext,
  @JsonValue('supplement')
supplement,
  @JsonValue('webpage')
webpage,
  @JsonValue('file-directory')
filedirectory,
  @JsonValue('code-repository')
coderepository,
  @JsonValue('restricted')
restricted,
  @JsonValue('compressed-file')
compressedfile,
  @JsonValue('doi-based')
doibased,
  @JsonValue('pdf')
pdf,
  @JsonValue('json')
json,
  @JsonValue('xml')
xml,
  @JsonValue('version-specific')
versionspecific,
  @JsonValue('computable-resource')
computableresource,
  @JsonValue('not-specified')
notspecified,
}

enum CitedArtifactClassificationType {
  @JsonValue('publication-type')
publicationtype,
  @JsonValue('mesh-heading')
meshheading,
  @JsonValue('supplemental-mesh-protocol')
supplementalmeshprotocol,
  @JsonValue('supplemental-mesh-disease')
supplementalmeshdisease,
  @JsonValue('supplemental-mesh-organism')
supplementalmeshorganism,
  @JsonValue('keyword')
keyword,
  @JsonValue('citation-subset')
citationsubset,
  @JsonValue('chemical')
chemical,
  @JsonValue('publishing-model')
publishingmodel,
  @JsonValue('knowledge-artifact-type')
knowledgeartifacttype,
  @JsonValue('coverage')
coverage,
}

enum CitationArtifactClassifier {
  @JsonValue('audio')
audio,
  @JsonValue('D001877')
d001877,
  @JsonValue('cds-artifact')
cdsartifact,
  @JsonValue('D016420')
d016420,
  @JsonValue('common-share')
commonshare,
  @JsonValue('D019991')
d019991,
  @JsonValue('D064886')
d064886,
  @JsonValue('dataset-unpublished')
datasetunpublished,
  @JsonValue('Electronic')
electronic,
  @JsonValue('Electronic-eCollection')
electronicecollection,
  @JsonValue('Electronic-Print')
electronicprint,
  @JsonValue('executable-app')
executableapp,
  @JsonValue('fhir-resource')
fhirresource,
  @JsonValue('image')
image,
  @JsonValue('interactive-form')
interactiveform,
  @JsonValue('D016428')
d016428,
  @JsonValue('D016422')
d016422,
  @JsonValue('machine-code')
machinecode,
  @JsonValue('medline-base')
medlinebase,
  @JsonValue('prediction-model')
predictionmodel,
  @JsonValue('D000076942')
d000076942,
  @JsonValue('Print')
print,
  @JsonValue('Print-Electronic')
printelectronic,
  @JsonValue('project-specific')
projectspecific,
  @JsonValue('protocol')
protocol,
  @JsonValue('pseudocode')
pseudocode,
  @JsonValue('D016425')
d016425,
  @JsonValue('standard-specification')
standardspecification,
  @JsonValue('terminology')
terminology,
  @JsonValue('D059040')
d059040,
  @JsonValue('webpage')
webpage,
}

enum ArtifactContributionType {
  @JsonValue('conceptualization')
conceptualization,
  @JsonValue('data-curation')
datacuration,
  @JsonValue('formal-analysis')
formalanalysis,
  @JsonValue('funding-acquisition')
fundingacquisition,
  @JsonValue('investigation')
investigation,
  @JsonValue('methodology')
methodology,
  @JsonValue('project-administration')
projectadministration,
  @JsonValue('resources')
resources,
  @JsonValue('software')
software,
  @JsonValue('supervision')
supervision,
  @JsonValue('validation')
validation,
  @JsonValue('visualization')
visualization,
  @JsonValue('writing-original-draft')
writingoriginaldraft,
  @JsonValue('writing-review-editing')
writingreviewediting,
}

enum ContributorRole {
  @JsonValue('publisher')
publisher,
  @JsonValue('author')
author,
  @JsonValue('reviewer')
reviewer,
  @JsonValue('endorser')
endorser,
  @JsonValue('editor')
editor,
  @JsonValue('informant')
informant,
  @JsonValue('funder')
funder,
}

enum ArtifactContributionInstanceType {
  @JsonValue('reviewed')
reviewed,
  @JsonValue('approved')
approved,
  @JsonValue('edited')
edited,
}

enum ContributorSummaryType {
  @JsonValue('author-string')
authorstring,
  @JsonValue('contributorship-list')
contributorshiplist,
  @JsonValue('contributorship-statement')
contributorshipstatement,
  @JsonValue('acknowledgement-list')
acknowledgementlist,
  @JsonValue('acknowledgment-statement')
acknowledgmentstatement,
  @JsonValue('funding-statement')
fundingstatement,
  @JsonValue('competing-interests-statement')
competinginterestsstatement,
}

enum ContributorSummaryStyle {
  @JsonValue('a1full')
a1full,
  @JsonValue('a1init')
a1init,
  @JsonValue('a3full')
a3full,
  @JsonValue('a3init')
a3init,
  @JsonValue('a6full')
a6full,
  @JsonValue('a6init')
a6init,
  @JsonValue('aallfull')
aallfull,
  @JsonValue('aallfullwithand')
aallfullwithand,
  @JsonValue('aallfullwithampersand')
aallfullwithampersand,
  @JsonValue('aallinit')
aallinit,
  @JsonValue('aallinitwithand')
aallinitwithand,
  @JsonValue('aallinitwithampersand')
aallinitwithampersand,
  @JsonValue('contr-full-by-person')
contrfullbyperson,
  @JsonValue('contr-init-by-person')
contrinitbyperson,
  @JsonValue('contr-full-by-contr')
contrfullbycontr,
  @JsonValue('contr-init-by-contr')
contrinitbycontr,
}

enum ContributorSummarySource {
  @JsonValue('publisher-data')
publisherdata,
  @JsonValue('article-copy')
articlecopy,
  @JsonValue('citation-manager')
citationmanager,
  @JsonValue('custom')
custom,
}

