enum VersionAlgorithm {
  @JsonValue('semver')
semver,
  @JsonValue('integer')
integer,
  @JsonValue('alpha')
alpha,
  @JsonValue('date')
date,
  @JsonValue('natural')
natural,
}

enum PublicationStatus {
  @JsonValue('draft')
draft,
  @JsonValue('active')
active,
  @JsonValue('retired')
retired,
  @JsonValue('unknown')
unknown,
}

enum StudyDesign {
  @JsonValue('SEVCO:01001')
sevco:01001,
  @JsonValue('SEVCO:01002')
sevco:01002,
  @JsonValue('SEVCO:01010')
sevco:01010,
  @JsonValue('SEVCO:01023')
sevco:01023,
  @JsonValue('SEVCO:01022')
sevco:01022,
  @JsonValue('SEVCO:01027')
sevco:01027,
  @JsonValue('SEVCO:01028')
sevco:01028,
  @JsonValue('SEVCO:01045')
sevco:01045,
  @JsonValue('SEVCO:01026')
sevco:01026,
  @JsonValue('SEVCO:01049')
sevco:01049,
  @JsonValue('SEVCO:01042')
sevco:01042,
  @JsonValue('SEVCO:01051')
sevco:01051,
  @JsonValue('SEVCO:01086')
sevco:01086,
  @JsonValue('SEVCO:01087')
sevco:01087,
  @JsonValue('SEVCO:01060')
sevco:01060,
  @JsonValue('SEVCO:01061')
sevco:01061,
  @JsonValue('SEVCO:01062')
sevco:01062,
  @JsonValue('SEVCO:01063')
sevco:01063,
  @JsonValue('SEVCO:01064')
sevco:01064,
  @JsonValue('SEVCO:01043')
sevco:01043,
  @JsonValue('SEVCO:01052')
sevco:01052,
  @JsonValue('SEVCO:01053')
sevco:01053,
  @JsonValue('SEVCO:01054')
sevco:01054,
  @JsonValue('SEVCO:01085')
sevco:01085,
  @JsonValue('SEVCO:01089')
sevco:01089,
}

enum StatisticModelCode {
  @JsonValue('oneTailedTest')
onetailedtest,
  @JsonValue('twoTailedTest')
twotailedtest,
  @JsonValue('zTest')
ztest,
  @JsonValue('oneSampleTTest')
onesamplettest,
  @JsonValue('twoSampleTTest')
twosamplettest,
  @JsonValue('pairedTTest')
pairedttest,
  @JsonValue('chiSquareTest')
chisquaretest,
  @JsonValue('chiSquareTestTrend')
chisquaretesttrend,
  @JsonValue('pearsonCorrelation')
pearsoncorrelation,
  @JsonValue('anova')
anova,
  @JsonValue('anovaOneWay')
anovaoneway,
  @JsonValue('anovaTwoWay')
anovatwoway,
  @JsonValue('anovaTwoWayReplication')
anovatwowayreplication,
  @JsonValue('manova')
manova,
  @JsonValue('anovaThreeWay')
anovathreeway,
  @JsonValue('signTest')
signtest,
  @JsonValue('wilcoxonSignedRankTest')
wilcoxonsignedranktest,
  @JsonValue('wilcoxonRankSumTest')
wilcoxonranksumtest,
  @JsonValue('mannWhitneyUTest')
mannwhitneyutest,
  @JsonValue('fishersExactTest')
fishersexacttest,
  @JsonValue('mcnemarsTest')
mcnemarstest,
  @JsonValue('kruskalWallisTest')
kruskalwallistest,
  @JsonValue('spearmanCorrelation')
spearmancorrelation,
  @JsonValue('kendallCorrelation')
kendallcorrelation,
  @JsonValue('friedmanTest')
friedmantest,
  @JsonValue('goodmanKruskasGamma')
goodmankruskasgamma,
  @JsonValue('glm')
glm,
  @JsonValue('glmProbit')
glmprobit,
  @JsonValue('glmLogit')
glmlogit,
  @JsonValue('glmIdentity')
glmidentity,
  @JsonValue('glmLog')
glmlog,
  @JsonValue('glmGeneralizedLogit')
glmgeneralizedlogit,
  @JsonValue('glmm')
glmm,
  @JsonValue('glmmProbit')
glmmprobit,
  @JsonValue('glmmLogit')
glmmlogit,
  @JsonValue('glmmIdentity')
glmmidentity,
  @JsonValue('glmmLog')
glmmlog,
  @JsonValue('glmmGeneralizedLogit')
glmmgeneralizedlogit,
  @JsonValue('linearRegression')
linearregression,
  @JsonValue('logisticRegression')
logisticregression,
  @JsonValue('polynomialRegression')
polynomialregression,
  @JsonValue('coxProportionalHazards')
coxproportionalhazards,
  @JsonValue('binomialDistributionRegression')
binomialdistributionregression,
  @JsonValue('multinomialDistributionRegression')
multinomialdistributionregression,
  @JsonValue('poissonRegression')
poissonregression,
  @JsonValue('negativeBinomialRegression')
negativebinomialregression,
  @JsonValue('zeroCellConstant')
zerocellconstant,
  @JsonValue('zeroCellContinuityCorrection')
zerocellcontinuitycorrection,
  @JsonValue('adjusted')
adjusted,
  @JsonValue('interactionTerm')
interactionterm,
  @JsonValue('manteHaenszelMethod')
mantehaenszelmethod,
  @JsonValue('metaAnalysis')
metaanalysis,
  @JsonValue('inverseVariance')
inversevariance,
  @JsonValue('petoMethod')
petomethod,
  @JsonValue('hartungKnapp')
hartungknapp,
  @JsonValue('modifiedHartungKnapp')
modifiedhartungknapp,
  @JsonValue('effectsFixed')
effectsfixed,
  @JsonValue('effectsRandom')
effectsrandom,
  @JsonValue('chiSquareTestHomogeneity')
chisquaretesthomogeneity,
  @JsonValue('dersimonianLairdMethod')
dersimonianlairdmethod,
  @JsonValue('pauleMandelMethod')
paulemandelmethod,
  @JsonValue('restrictedLikelihood')
restrictedlikelihood,
  @JsonValue('maximumLikelihood')
maximumlikelihood,
  @JsonValue('empiricalBayes')
empiricalbayes,
  @JsonValue('hunterSchmidt')
hunterschmidt,
  @JsonValue('sidikJonkman')
sidikjonkman,
  @JsonValue('hedgesMethod')
hedgesmethod,
  @JsonValue('tauDersimonianLaird')
taudersimonianlaird,
  @JsonValue('tauPauleMandel')
taupaulemandel,
  @JsonValue('tauRestrictedMaximumLikelihood')
taurestrictedmaximumlikelihood,
  @JsonValue('tauMaximumLikelihood')
taumaximumlikelihood,
  @JsonValue('tauEmpiricalBayes')
tauempiricalbayes,
  @JsonValue('tauHunterSchmidt')
tauhunterschmidt,
  @JsonValue('tauSidikJonkman')
tausidikjonkman,
  @JsonValue('tauHedges')
tauhedges,
  @JsonValue('poolMantelHaenzsel')
poolmantelhaenzsel,
  @JsonValue('poolInverseVariance')
poolinversevariance,
  @JsonValue('poolPeto')
poolpeto,
  @JsonValue('poolGeneralizedLinearMixedModel')
poolgeneralizedlinearmixedmodel,
}

enum VariableHandling {
  @JsonValue('continuous')
continuous,
  @JsonValue('dichotomous')
dichotomous,
  @JsonValue('ordinal')
ordinal,
  @JsonValue('polychotomous')
polychotomous,
}

enum CertaintyType {
  @JsonValue('Overall')
overall,
  @JsonValue('RiskOfBias')
riskofbias,
  @JsonValue('Inconsistency')
inconsistency,
  @JsonValue('Indirectness')
indirectness,
  @JsonValue('Imprecision')
imprecision,
  @JsonValue('PublicationBias')
publicationbias,
  @JsonValue('DoseResponseGradient')
doseresponsegradient,
  @JsonValue('PlausibleConfounding')
plausibleconfounding,
  @JsonValue('LargeEffect')
largeeffect,
}

enum CertaintyRating {
  @JsonValue('high')
high,
  @JsonValue('moderate')
moderate,
  @JsonValue('low')
low,
  @JsonValue('very-low')
verylow,
  @JsonValue('no-concern')
noconcern,
  @JsonValue('serious-concern')
seriousconcern,
  @JsonValue('very-serious-concern')
veryseriousconcern,
  @JsonValue('extremely-serious-concern')
extremelyseriousconcern,
  @JsonValue('present')
present,
  @JsonValue('absent')
absent,
  @JsonValue('no-change')
nochange,
  @JsonValue('downcode1')
downcode1,
  @JsonValue('downcode2')
downcode2,
  @JsonValue('downcode3')
downcode3,
  @JsonValue('upcode1')
upcode1,
  @JsonValue('upcode2')
upcode2,
}

